PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
         skos:prefLabel ?rdfs_label ;
         skos:altLabel ?schema_alternateName ;
         skos:altLabel ?schema_name ;
         skos:altLabel ?foaf_name ;
         skos:scopeNote ?rdfs_comment .
}
WHERE {
    ?uri schema:mainEntityOfPage/schema:isPartOf <http://data.bibliotheken.nl/id/dataset/persons> .
    ?uri ?predicate ?label .
    VALUES ?predicate { rdfs:label schema:name schema:alternateName foaf:name}

    # Replace query "A B" with "A AND B", leaving queries "A AND B" or "A OR B" unchanged.
    FILTER (<bif:contains> (?label, REPLACE(?query, "(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)", " AND ", "i")))

    OPTIONAL { ?uri rdfs:label ?rdfs_label }
    OPTIONAL { ?uri rdfs:comment ?rdfs_comment }
    OPTIONAL { ?uri schema:name ?schema_name }
    OPTIONAL { ?uri foaf:name ?foaf_name }
    OPTIONAL { ?uri schema:alternateName ?schema_alternateName }
}
LIMIT 1000
