PREFIX dbo:	<http://dbpedia.org/ontology/>
PREFIX dbr:	<http://dbpedia.org/resource/>
PREFIX ns34: <http://purl.org/linguistics/gold/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
    skos:prefLabel ?foaf_name ;
    skos:scopeNote ?dbo_abstract .
}
WHERE {
    ?uri ns34:hypernym dbr:Astronomer .
    ?uri foaf:name ?foaf_name .
    FILTER(CONTAINS(LCASE(?foaf_name), LCASE(?searchTerms)))
    OPTIONAL { ?uri dbo:abstract ?dbo_abstract }
}
LIMIT 50
