CONSTRUCT { 
    ?uri a skos:Concept ; 
         skos:prefLabel ?prefLabel ; 
         skos:altLabel ?altLabel ; 
         skos:scopeNote ?scopeNote 
}
WHERE { 
    graph <http://data.bibliotheken.nl/thesp/> {
      ?uri a schema:Person . 
      { 
        ?uri rdfs:label ?label .
        FILTER(CONTAINS(LCASE(?label), LCASE(?searchTerm)))
      } 
      UNION 
      {
        ?uri schema:name ?label .
        FILTER(CONTAINS(LCASE(?label), LCASE(?searchTerm)))
      }
      UNION 
      {
        ?uri schema:alternateName ?label .
        FILTER(CONTAINS(LCASE(?label), LCASE(?searchTerm)))
      }
      OPTIONAL { ?uri rdfs:label ?prefLabel }
      OPTIONAL { ?uri rdfs:comment ?scopeNote }
      OPTIONAL { ?uri schema:name ?altLabel }
      OPTIONAL { ?uri schema:alternateName ?altLabel }
   }
}
LIMIT 1000