PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
    skos:prefLabel ?schema_name ;
}
WHERE {
    ?uri schema:name ?schema_name .
    FILTER(LANG(?schema_name) = "nl")
    FILTER(CONTAINS(LCASE(?schema_name), LCASE(?searchTerms)))
}
LIMIT 50
