PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
    skos:prefLabel ?prefLabel ;
}
WHERE {
    # ?uri a ?type .
    # VALUES ?type { schema:Person }
    ?uri schema:name ?prefLabel .
    FILTER(LANG(?prefLabel) = "nl")
    FILTER(CONTAINS(LCASE(?prefLabel), LCASE(?searchTerm)))
}
LIMIT 50
