name: Nx migrate

on:
  schedule:
    - cron: '0 6 * * *' # Every night at 06:00 UTC
  workflow_dispatch:

jobs:
  migrate:
    uses: netwerk-digitaal-erfgoed/workflows/.github/workflows/nx-migrate.yml@main
    secrets: inherit
